steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-doc-generator-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-doc-generator-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-doc-generator-backend'
      - '--image=gcr.io/$PROJECT_ID/ai-doc-generator-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=HF_MODEL=${_HF_MODEL}'
      - '--set-secrets=HF_API_KEY=hf-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_KEY=supabase-key:latest,N8N_GITHUB_WEBHOOK=n8n-webhook:latest'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ai-doc-generator-backend:$COMMIT_SHA'

substitutions:
  _HF_MODEL: 'mistralai/Mistral-7B-Instruct-v0.2'  # Default model, can be overridden 