apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-db-data
  namespace: eu-ai-act
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-db
  namespace: eu-ai-act
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-db
  template:
    metadata:
      labels:
        app: vector-db
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: QDRANT__SERVICE__HTTP_PORT
          value: "6333"
        - name: QDRANT__SERVICE__GRPC_PORT
          value: "6334"
        # Set minimal memory consumption
        - name: QDRANT__STORAGE__OPTIMIZERS__INDEXING_THRESHOLD_KB
          value: "10000"  # 10MB instead of default 20MB
        - name: QDRANT__STORAGE__OPTIMIZERS__VACUUM_MIN_VECTOR_NUMBER
          value: "1000"  # Lower vacuum threshold
        - name: QDRANT__STORAGE__OPTIMIZERS__DEFAULT_SEGMENT_NUMBER
          value: "2"  # Use fewer segments to reduce memory
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: vector-db-data
          mountPath: /qdrant/storage
        livenessProbe:
          httpGet:
            path: /
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 6333
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: vector-db-data
        persistentVolumeClaim:
          claimName: vector-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: vector-db
  namespace: eu-ai-act
spec:
  type: ClusterIP
  ports:
  - port: 6333
    targetPort: 6333
    protocol: TCP
    name: http
  - port: 6334
    targetPort: 6334
    protocol: TCP
    name: grpc
  selector:
    app: vector-db 